### ISSUE TITLE
Adding warning (or disable) the 'w' mode for HDF5DAS

### ISSUE THREAD

**Issue by hilarych** [malcolmw/HDF5eis#1]
Hi Malcolm, do you think it would be safer if we disable the ‘w’ mode or add warning in the dash module? I find if we accidentally use ‘w’ when reading the data the entire file would be formated.

**Comment by malcolmw** [comment]
Good point, @HilaryCh. I will add a `safe_mode` keyword argument to the constructor that will default to `safe_mode=True`. If the user tries to open a file with `mode="w", safe_mode=True` and the file already exists, the code will complain. If the file does not exist, it will open like usual. If the user wants to overwrite an existing file, the can open it with `mode="w", safe_mode=False`.

**Comment by malcolmw** [comment]
OK, I [added this feature](https://github.com/malcolmw/dash/commit/02efa32ada393aa78f246c0b216e83d8d6899501) to the code.
